import qrcode1 from './assets/img1.png'
import poster50lakh from './assets/poster50lakh.jpg'
import poster3lakh from './assets/poster3lakh.jpg'
import fund3lakh from './assets/fund3lakh.jpg'
import banner from './assets/banner.jpg'
import Become from './assets/Become.jpg'
import WealthX from './assets/WealthX.png'
import WealthX2 from './assets/WealthX.jpg'
import WealthX3 from './assets/WealthX3.png'
import companyLogo from "./assets/landingPageImg/company_logo-1.webp"
import companyLogo2 from "./assets/landingPageImg/company_logo2.webp"
import companyLogo3 from "./assets/landingPageImg/company_logo5.webp"
import companyLogo4 from "./assets/landingPageImg/company_logo6.webp"
import cryptobgless from "./assets/landingPageImg/cryptobgless.png"
import teampng from "./assets/landingPageImg/team.jpg"
import tradeon2 from "./assets/landingPageImg/trade_on2.webp"
import sunIcon from "./assets/landingPageImg/sunIcon.png"
import starIcon from "./assets/landingPageImg/starIcon.png"
import whytradebg from "./assets/landingPageImg/why_trade_bg.webp"
import girlwithphone from "./assets/landingPageImg/why_trade_girl.webp"
import vectorIcon from "./assets/landingPageImg/trade_vector_icon.webp"
import phoneGirl from "./assets/landingPageImg/phone_girl.webp"
import vectorRocket from "./assets/landingPageImg/vector_rocket-1.webp"
import Lead1 from "./assets/landingPageImg/Lead-1.webp"
import Lead2 from "./assets/landingPageImg/Lead-2.webp"
import Lead3 from "./assets/landingPageImg/Lead-3.webp"
import Lead4 from "./assets/landingPageImg/Lead-4.webp"
import faqimg from "./assets/landingPageImg/faq.webp"
import author1 from "./assets/landingPageImg/author-1.webp"
import author2 from "./assets/landingPageImg/author-2.webp"
import author3 from "./assets/landingPageImg/author-3.webp"
import mobileStar from "./assets/landingPageImg/hero_mobile_star.webp"
import bgImg from "./assets/Accounts/bg.webp"
import AccountImg from "./assets/Accounts/account-4-1-1.webp"
import companyStory from "./assets/About/company_story.webp";
import apple from "./assets/GreenTab/Apple.jpg";
import etheriumQrCode from "./assets/Accounts/EtheriumQrCode.jpg";
import etherium from "./assets/GreenTab/Etherium.jpg";
import bitcoin from "./assets/GreenTab/Bitcoin.jpg";
import bse from "./assets/GreenTab/BSE.jpg";
import bajajFinance from "./assets/GreenTab/BajajFinance.jpg";
import bhartaElectronics from "./assets/GreenTab/BhartaElectronics.jpg";
import itcLimited from "./assets/GreenTab/ItcLimited.jpg";
import hero from "./assets/GreenTab/Hero.jpg";
import ultratechCement from "./assets/GreenTab/UltratechCement.jpg";
import jswSteel from "./assets/GreenTab/JSW_Steel.jpg";
import hcl from "./assets/GreenTab/HCL.jpg";
import financialServices from "./assets/GreenTab/FinancialServices.jpg";
import ongc from "./assets/GreenTab/ONGC.jpg";
import reliance from "./assets/GreenTab/Reliance.jpg";
import shriramFinance from "./assets/GreenTab/ShriramFinance.jpg";
import larsenAndToubro from "./assets/GreenTab/Larsen&Toubro.jpg";
import mrf from "./assets/GreenTab/MRF.jpg";
import tataMotors from "./assets/GreenTab/TataMotors.jpg";
import sbi from "./assets/GreenTab/SBI.jpg";
import iciciBank from "./assets/GreenTab/ICICI_Bank.jpg";
import hdfcBank from "./assets/GreenTab/HDFC_Bank.jpg";
import spBseSensex from "./assets/GreenTab/s&pBseSensex.jpg";
import niftySmallcap from "./assets/GreenTab/niftysmallcap.jpg";
import niftyMidcap from "./assets/GreenTab/niftymidcap.jpg";
import niftyBank from "./assets/GreenTab/niftybank.jpg";
import nifty50 from "./assets/GreenTab/nifty50.jpg";
import bankAccount from "./assets/Accounts/BankAccount.jpeg";
import WealthxHome from "./assets/landingPageImg/WealthX1.jpg";
import StopScrolling from "./assets/other/StopScrolling.jpeg";
import SkillNeed from "./assets/other/SkillNeed.jpeg";
import NoCapital from "./assets/other/NoCapital.jpeg";
import GrowWithUs from "./assets/other/GrowWithUs.jpeg";
import BiggestMistake from "./assets/other/BiggestMistake.jpeg";
import Get50Lakh from "./assets/other/get50Lakh.jpeg";
import MostTrusted from "./assets/other/MostTrusted.jpeg";
import AffordableTrading from "./assets/other/AffordableTrading.jpeg";
import FundsProblem from "./assets/other/fundsProblem.jpeg";




export {qrcode1, poster3lakh, poster50lakh, fund3lakh, banner, Become, WealthX, WealthX2, WealthX3, companyLogo, companyLogo2, companyLogo3, companyLogo4, cryptobgless, teampng, tradeon2, sunIcon, starIcon, whytradebg, girlwithphone, vectorIcon, phoneGirl, vectorRocket, Lead1, Lead2, Lead3, Lead4, faqimg, author1, author2, author3, mobileStar, bgImg, AccountImg, companyStory, apple, etherium, etheriumQrCode, bajajFinance, bhartaElectronics, bitcoin, bse, itcLimited, hero, ultratechCement, jswSteel, hcl, financialServices, ongc, reliance, shriramFinance, larsenAndToubro, mrf, tataMotors, sbi, iciciBank, hdfcBank, spBseSensex, nifty50, niftyBank, niftyMidcap, niftySmallcap, bankAccount, WealthxHome, StopScrolling, SkillNeed, NoCapital, GrowWithUs, BiggestMistake, Get50Lakh, MostTrusted, AffordableTrading, FundsProblem,};